2023-11-24 18:27:20,337:DEBUG:certbot._internal.main:certbot version: 2.7.4
2023-11-24 18:27:20,337:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2023-11-24 18:27:20,337:DEBUG:certbot._internal.main:Arguments: ['--config-dir', 'letsencrypt/config', '--work-dir', 'letsencrypt', '--logs-dir', 'letsencrypt/logs', '--authenticator', 'dns-ionos', '--dns-ionos-credentials', 'letsencrypt/.secrets/ionos-credentials.ini', '--dns-ionos-propagation-seconds', '900', '--server', 'https://acme-v02.api.letsencrypt.org/directory', '--agree-tos', '--non-interactive', '--rsa-key-size', '4096', '-m', 'admin@marmilan.com', '-d', 'picluster.marmilan.com']
2023-11-24 18:27:20,340:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#dns-ionos,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2023-11-24 18:27:20,354:DEBUG:certbot._internal.log:Root logging level set at 30
2023-11-24 18:27:20,361:DEBUG:certbot._internal.plugins.selection:Requested authenticator dns-ionos and installer None
2023-11-24 18:27:20,361:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * dns-ionos
Description: Obtain certificates using a DNS TXT record (if you are using IONOS for DNS).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='dns-ionos', value='certbot_dns_ionos.dns_ionos:Authenticator', group='certbot.plugins')
Initialized: <certbot_dns_ionos.dns_ionos.Authenticator object at 0x7f4319e687a0>
Prep: True
2023-11-24 18:27:20,362:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot_dns_ionos.dns_ionos.Authenticator object at 0x7f4319e687a0> and installer None
2023-11-24 18:27:20,362:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator dns-ionos, Installer None
2023-11-24 18:27:21,014:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/1431695516', new_authzr_uri=None, terms_of_service=None), 99bacc5fcc99908c8befa91e1c243edc, Meta(creation_dt=datetime.datetime(2023, 11, 24, 18, 27, 1, tzinfo=<UTC>), creation_host='d28e295fc7c4', register_to_eff=None))>
2023-11-24 18:27:21,015:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2023-11-24 18:27:21,017:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2023-11-24 18:27:21,598:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 752
2023-11-24 18:27:21,599:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 24 Nov 2023 18:27:09 GMT
Content-Type: application/json
Content-Length: 752
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "ons8dsIfroE": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-01/renewalInfo/",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2023-11-24 18:27:21,600:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for picluster.marmilan.com
2023-11-24 18:27:21,611:DEBUG:acme.client:Requesting fresh nonce
2023-11-24 18:27:21,612:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2023-11-24 18:27:21,802:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2023-11-24 18:27:21,803:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 24 Nov 2023 18:27:10 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: nbWKegf8IU55-Nzmym1xo7ABUH6l67Voyx0wNA9WTlUzlAg2Spg
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2023-11-24 18:27:21,803:DEBUG:acme.client:Storing nonce: nbWKegf8IU55-Nzmym1xo7ABUH6l67Voyx0wNA9WTlUzlAg2Spg
2023-11-24 18:27:21,803:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "picluster.marmilan.com"\n    }\n  ]\n}'
2023-11-24 18:27:21,818:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTQzMTY5NTUxNiIsICJub25jZSI6ICJuYldLZWdmOElVNTUtTnpteW0xeG83QUJVSDZsNjdWb3l4MHdOQTlXVGxVemxBZzJTcGciLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "uvkbSHyqyB4P6rdzp1yBgNnEu6nPl4-daFs7YHz1x5Kg4neXdtbGg1msgq1zPGa0clW0fai1M5DB2cCbDAw7iXj9e20FeCv8H9MhCqSXOJ5b8S4rgyQMB_OpCRkvA0LdkBkEXlSaBvJAGy_9bX9FWPYv55L2Uu4yR6Gng8D9rzoi5YoyliTudGvZPmKeWv5wZ0iE5lnPGJ_1kSm4GmmpRJoTFy1NYFPOPCEVSetwfScM1jiWO3EAxqYbkTI-WtXk1xu0unaRKrxWCzJloH2Y53VrLCtBuRgPD-1s-rGgJ5dZ_05poqM7ULvrADQZP8n2hJ81fdyUjpDi1pAuAtgKAOdfUjVQJjKoV8fZ9Fz5EpbWCf2URrPdXjF6nGs-m8lasMNW0jos7146YwhxTTf6ygHb1JJ6ikrvhJD6Uf0CPJj5A45ZiZ2OZXZ4qx-AmMg6st3ZtogENh8yBKaaiELthdEGl406Yf79vTXOy-H4rTeUUQZsLnBZVtYOAENNpM1fjDmmIB23lR_BzbED4Aw_GTOuAI4Z2Lm-VlcoSYQQRq8BVpLd7qau8y-c47Igr2QQOV52cgUVNNwvm7S4bHoZUznwd-0a1YEM_eVidJzTFqhsSIYSBLuYq8y5mh_o6ptzCPeNyT6w0EET_7863bSG-P-an9GnZZg06DexZVG845Q",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInBpY2x1c3Rlci5tYXJtaWxhbi5jb20iCiAgICB9CiAgXQp9"
}
2023-11-24 18:27:22,009:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 348
2023-11-24 18:27:22,009:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Fri, 24 Nov 2023 18:27:10 GMT
Content-Type: application/json
Content-Length: 348
Connection: keep-alive
Boulder-Requester: 1431695516
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/1431695516/224538486486
Replay-Nonce: nbWKegf8rKH9A5heoPsDkmPQ_rPG_7KCtFbmrB7IwRDgiiRPdYw
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2023-12-01T18:26:50Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "picluster.marmilan.com"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/287125320086"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/1431695516/224538486486"
}
2023-11-24 18:27:22,010:DEBUG:acme.client:Storing nonce: nbWKegf8rKH9A5heoPsDkmPQ_rPG_7KCtFbmrB7IwRDgiiRPdYw
2023-11-24 18:27:22,010:DEBUG:acme.client:JWS payload:
b''
2023-11-24 18:27:22,021:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/287125320086:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTQzMTY5NTUxNiIsICJub25jZSI6ICJuYldLZWdmOHJLSDlBNWhlb1BzRGttUFFfclBHXzdLQ3RGYm1yQjdJd1JEZ2lpUlBkWXciLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzI4NzEyNTMyMDA4NiJ9",
  "signature": "NriMGWU9bY8rX9Y3yCAF4Y7Kl9VGdzU2Pru-jmGRSWrbc555JCaXD9JjuvpAfPjcSbyDD0GULUq4Ot39ebc6AM5JUq5r49vFX9qi6G2ioynAbQuRfib4tvsqV26CrclapbkornlhxMVMeQKKhsD6pD_heWdPljvrI3GyIxH_WVpl2W6Py1EMlZceKO065dzRSZcaGFMVr3Z30OlydI6F82IbymTuAtcpc66a_weM5dx7qCR9Isbyj7LgsGFNzO37MF5wwZ1zIkIS_kcYvpb5OXpEJRQdFrZ2s8YqdVRsNwRF5X0L2n25lkM4X8AqJY9jrcOJ2t0UEykKfpGmCEMIz-sPSBK6-_mm9qRMm-cM6KqYZDxlR6jtqJEYfvLITGVG8I-aYPNENKZTeMAZOvglkhGVhLrExRrnIG6wDRibcSg2X9HtQWblSNUzzVTqmjbwuw_th1joG2BW0LQqJCxLILU9tDRoaKLW76eHVshw9yNySJocQwEb4wZ3AqB4GNxM5M7tS8P5mPr7Z8pYCdivBMKNY-DnNYpImfSOwUR_rT2GyJ_wKVCdw4tYR74CEoyMDFZiTEG5pVHpk3IBriV2QGJ3nGdK10aW82zy6tem1i5GwwobC46PIfzZgKdyde5GhSUCa_RlzCtNt--5G0oPQD7Z624BsvIQNEhJL-z3pao",
  "payload": ""
}
2023-11-24 18:27:22,210:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/287125320086 HTTP/1.1" 200 806
2023-11-24 18:27:22,210:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 24 Nov 2023 18:27:10 GMT
Content-Type: application/json
Content-Length: 806
Connection: keep-alive
Boulder-Requester: 1431695516
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: v0bMowfiNKiLnLaneDMqUNTxR32BEgN4sppglAQMwylltCHimwc
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "picluster.marmilan.com"
  },
  "status": "pending",
  "expires": "2023-12-01T18:26:50Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/287125320086/6y9Qbw",
      "token": "eSU88QbPv3xTBo-ZeHLHtH0Qi_riemwlMCt1M66EgOE"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/287125320086/dprw5Q",
      "token": "eSU88QbPv3xTBo-ZeHLHtH0Qi_riemwlMCt1M66EgOE"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/287125320086/cQ7fOw",
      "token": "eSU88QbPv3xTBo-ZeHLHtH0Qi_riemwlMCt1M66EgOE"
    }
  ]
}
2023-11-24 18:27:22,210:DEBUG:acme.client:Storing nonce: v0bMowfiNKiLnLaneDMqUNTxR32BEgN4sppglAQMwylltCHimwc
2023-11-24 18:27:22,211:INFO:certbot._internal.auth_handler:Performing the following challenges:
2023-11-24 18:27:22,211:INFO:certbot._internal.auth_handler:dns-01 challenge for picluster.marmilan.com
2023-11-24 18:27:22,213:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/certbot/plugins/dns_common.py", line 66, in perform
    self._setup_credentials()
  File "/usr/local/lib/python3.12/site-packages/certbot_dns_ionos/dns_ionos.py", line 40, in _setup_credentials
    self.credentials = self._configure_credentials(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/certbot/plugins/dns_common.py", line 195, in _configure_credentials
    credentials_configuration = CredentialsConfiguration(self.conf(key), self.dest)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/certbot/plugins/dns_common.py", line 270, in __init__
    validate_file_permissions(filename)
  File "/usr/local/lib/python3.12/site-packages/certbot/plugins/dns_common.py", line 345, in validate_file_permissions
    validate_file(filename)
  File "/usr/local/lib/python3.12/site-packages/certbot/plugins/dns_common.py", line 336, in validate_file
    raise errors.PluginError('File not found: {0}'.format(filename))
certbot.errors.PluginError: File not found: letsencrypt/.secrets/ionos-credentials.ini

2023-11-24 18:27:22,213:DEBUG:certbot._internal.error_handler:Calling registered functions
2023-11-24 18:27:22,213:INFO:certbot._internal.auth_handler:Cleaning up challenges
2023-11-24 18:27:22,214:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/certbot/_internal/main.py", line 1873, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/certbot/_internal/main.py", line 1600, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/certbot/_internal/main.py", line 143, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/certbot/plugins/dns_common.py", line 66, in perform
    self._setup_credentials()
  File "/usr/local/lib/python3.12/site-packages/certbot_dns_ionos/dns_ionos.py", line 40, in _setup_credentials
    self.credentials = self._configure_credentials(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/certbot/plugins/dns_common.py", line 195, in _configure_credentials
    credentials_configuration = CredentialsConfiguration(self.conf(key), self.dest)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/certbot/plugins/dns_common.py", line 270, in __init__
    validate_file_permissions(filename)
  File "/usr/local/lib/python3.12/site-packages/certbot/plugins/dns_common.py", line 345, in validate_file_permissions
    validate_file(filename)
  File "/usr/local/lib/python3.12/site-packages/certbot/plugins/dns_common.py", line 336, in validate_file
    raise errors.PluginError('File not found: {0}'.format(filename))
certbot.errors.PluginError: File not found: letsencrypt/.secrets/ionos-credentials.ini
2023-11-24 18:27:22,216:ERROR:certbot._internal.log:File not found: letsencrypt/.secrets/ionos-credentials.ini
